home/urls.py
from django.urls import path, include
from .views import IndexView, SignUpDoneView, SignUp,Product1, detail,AboutView,noidung_baiviet,addcart,Contact
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from . import views



app_name = 'home'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('signup/', SignUp.as_view(success_url=reverse_lazy('home:signup_done')), name='signup'),
    path('signup/done/', SignUpDoneView.as_view(), name='signup_done'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),



    path('', IndexView.as_view(), name='home'),
    path('product/', Product1.as_view(), name='product'),
    path('<int:pk>/' , detail , name='detail'),
    path('about/', AboutView.as_view(), name='about'),
    path('about/<int:pk>', noidung_baiviet, name='noidung_baiviet'),
    path('addcart',views.addcart, name = 'addcart'),
    path('contact/', Contact.as_view(), name='contact'),
    path('shoppingcart/',views.shoppingcart,name = 'shoppingcart'),
    path('checkout/',views.checkout, name = 'checkout'),
    path('confirmCart',views.confirmCart, name = 'confirmCart')

]

shop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


# Create your models here.

#Product
class Category(models.Model):
    title = models.CharField(max_length=100,default='')
    description = models.TextField(default='')
    active = models.BooleanField(default=True)

class Product(models.Model):
    title = models.CharField(max_length=255,default='')
    description = models.TextField(default='')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    product_img = models.CharField(max_length=255,default='')
    price = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=255,default='')
    price = models.IntegerField(default=0)
    sale_price = models.IntegerField(default=0)
    investory = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

class BaiViet(models.Model):
    baiviet_id = models.IntegerField(auto_created=True, primary_key=True)
    tieude = models.CharField(max_length=300)
    noidung = models.TextField()
    ngay_dang = models.DateTimeField(default=timezone.now)
    anhbia = models.CharField(max_length=300)


class Order(models.Model):
    order_id = models.AutoField(primary_key = 'true')
    custom = models.CharField(max_length=200)
    address = models.TextField(max_length=1000,default='')
    phone = models.CharField(max_length=15,default='')
    total = models.FloatField()
    date_create = models.DateTimeField(default=timezone.now)
    note = models.TextField()
    payment_status = models.IntegerField(blank=True,null=True)
    status = models.IntegerField()
    accept = models.BooleanField(default=False)


class OrderDetail(models.Model):
    detail_id = models.AutoField(primary_key = 'true')
    pro_name = models.CharField(max_length=255,default='')
    orders = models.ForeignKey('Order', on_delete=models.CASCADE)
    pro_price = models.IntegerField(null=False)
    pro_image = models.CharField(max_length=255,default='')
    quantity = models.IntegerField(null=False)
    status = models.SmallIntegerField(blank=True,null=True)

home/views.py
from django.views.generic import TemplateView, CreateView, DetailView
from  django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import render
from .models import Product, Category,BaiViet,Order,OrderDetail
from django.template.loader import render_to_string
from django.http import HttpResponse


from django.contrib.auth import authenticate,login
from django.views import View

from django.http import HttpResponseRedirect

#View đăng ký người dùng
class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

#View đăng ký người dùng thành công
class SignUpDoneView(TemplateView):
    template_name = 'registration/signup_done.html'
    title = 'Signup successful'

#View hiển thị trang chủ (index.html)
class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        categories = Category.objects.all()
        product = Product.objects.all()[:6]
        context = {
            'categorys': categories,
            'products' : product,
        }
        return context

class Product1(TemplateView):
    template_name = "shop.html"

    def get_context_data(self, **kwargs):
        categories = Category.objects.all()
        product = Product.objects.all()
        context = {
            'categorys1': categories,
            'products1': product,
        }
        return context



def detail(request, pk):
    detail = Product.objects.get(pk=pk)
    context = {
        'detail': detail,
        'id': pk,
        }
    return render(request, 'product_detail.html', context)

class AboutView(TemplateView):
    template_name = "aboutus.html"

    def get_context_data(self, **kwargs):
        context = dict()
        baiviets = BaiViet.objects.all()
        context['baiviets'] = baiviets
        return context


def noidung_baiviet(request, pk):
    baiviet = BaiViet.objects.get(pk=pk)
    # print(binhluans)
    context = {
        'baiviet': baiviet,
        'baiviet_id':pk
        }
    return render(request, 'post.html', context)

class Contact(TemplateView):
    template_name = "contact.html"

cart = {}
def addcart(request):
    if request.is_ajax():
        id = request.POST.get('id')
        num = request.POST.get('num')
        proDetail = Product.objects.get(id = id)
        if id in cart.keys():
            itemCart = {
                'name':proDetail.title,
                'price':proDetail.price,
                'image': str(proDetail.product_img),
                'num': int(cart[id]['num']) +1
            }
        else:
            itemCart = {
                'name': proDetail.title,
                'price': proDetail.price,
                'image': str(proDetail.product_img),
                'num': num
            }
        cart[id] = itemCart
        request.session['cart'] = cart
        cartInfo = request.session['cart']
        html = render_to_string('addcart.html',{'cart':cartInfo})
    return HttpResponse(html)

def shoppingcart(request):
    total = 0;
    carts = request.session['cart']
    for key,value in carts.items():
        total += int(value['price'])* int(value['num'])
    return render(request,'cart.html',{'total':total})



def checkout(request):
    total = 0;
    carts = request.session['cart']
    for key, value in carts.items():
        total += int(value['price']) * int(value['num'])
    context = {'carts': carts,'total':total}
    return render(request, 'checkout.html', {'total': total,'carts':carts,})

def confirmCart(request):
    if request.method == 'POST':
        new_order = request.POST.get("order_id")
        address = request.POST.get("address")
        custom = request.POST.get("custom")
        note = request.POST.get("note")
        phone = request.POST.get("phone")

        total = 0;
        carts = request.session['cart']
        for key, value in carts.items():
            total += int(value['price']) * int(value['num'])
        context = {'carts': carts, 'total': total}
        orders = Order(order_id = new_order, address = address,custom = custom,note = note,phone = phone, total = total,payment_status = 0,status = 0,accept= False)
        orders.save()
        for key, value in carts.items():
            orderdetail = OrderDetail(orders = orders, pro_name = value['name'],pro_price = value['price'],pro_image = value['image'],quantity =value['num'],status = 0 )
            orderdetail.save()
        context = {
            'order_id': new_order,
            'address' :address,
            'custom':custom,
            'note':note,
            'phone':phone,
            'total': total,
            'orders': orders,
            'pro_name': value['name'],
            'pro_price':value['price'],
            'pro_image': value['image'],
            'quantity': value['num']

        }
        return render(request,'checkout.html',context)

home/templates/aboutus.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
{% for baiviet in baiviets %}
<div class="container">
    <!-- Blog Post -->
    <div class="card mb-4">
            <a href="{% url 'home:noidung_baiviet' baiviet.pk %}">
                <center ><img class="card-img-top" src="{{ baiviet.anhbia }}" alt="Card image cap" style="height: 700px;width: 1140px"></center>
        </a>
        <div class="card-body">
            <h2 class="card-title">{{ baiviet.tieude }}</h2>
            <p class="card-text" style="font-size:20px ">{{ baiviet.noidung|slice:"0:250" }} . . .

                <a class="btn btn-sm btn-outline-primary" href="{% url 'home:noidung_baiviet' baiviet.pk %}" style="font-size:20px ">Đọc
                    tiếp</a></p>
        </div>
    </div>
</div>
    {% endfor %}
{% endblock content %}

home/templates/account_page.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% endblock content %}

home/templates/addcart.html
{{cart}}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">


</head><!--/head-->

<body>
{% block header %}
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> 0123456788</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row" style="background-color: #8A0808 !important;" >
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="{% static 'images/home/logo2.png' %}" width="200" height="100" ></a>
						</div>

					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right" >
							<ul class="nav navbar-nav" >

								<li><a href="{% url 'home:shoppingcart' %}" style="color: white !important;font-weight: bold;font-size: 20px;background-color: #8A0808 !important;"><i class="fa fa-shopping-cart"></i> Giỏ hàng</a></li>
								{% if user.is_authenticated %}
								<li class="nav-item">
									<a class="nav-link" href="{% url 'home:logout' %}" style="color: white !important;font-weight: bold;font-size: 20px;background-color: #8A0808 !important;"><i class="fa fa-lock"></i>
										{% if user.first_name %}
										Hi {{ user.first_name }}!
										{% else %}
										Hi {{ user.username }}!
										{% endif %}
										Đăng xuất</a>
								</li>
								{% else %}
								<li class="nav-item">
									<a class="nav-link" href="{% url 'home:login' %}">Đăng nhập</a>
								</li>
                				{% endif %}

                                <br>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="index.html" class="active">Trang chủ</a></li>
								<li><a href="{% url 'home:product' %}">Thực đơn</a>
                                </li>
								<li ><a href="{% url 'home:about' %}">Về chúng tôi</a>
                                </li>
								<li><a href="{% url 'home:contact' %}">Liên hệ</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right"  >
							<input type="text" placeholder="Search" style="width:400px;  background-position: 340px;font-size:15px"/>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
<footer id="footer"style="background-color: #8A0808 !important;"><!--Footer-->
		<div class="footer-top">
			<div class="container" >
				<div class="row"  >

				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container" >
				<div class="row" >
					<div class="col-sm-2"  >
						<div class="single-widget" >
							<h2 style="color:white;font-size:18px;">Liên hệ </h2>
							<ul class="nav nav-pills nav-stacked">
								<li ><a href="#" style="color:white;font-size:18px;">Email</a></li>
								<li ><a href="#" style="color:white;font-size:18px;">Facebook</a></li>
								<li ><a href="#" style="color:white;font-size:18px;">Instagram</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2 style="color:white;font-size:18px;">Danh mục </h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#" style="color:white;font-size:18px;">Coffee</a></li>
								<li><a href="#" style="color:white;font-size:18px;">Freeze</a></li>
								<li><a href="#" style="color:white;font-size:18px;">Tea</a></li>
								<li><a href="#" style="color:white;font-size:18px;">Bread</a></li>
							</ul>
						</div>
					</div>

					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2 style="color:white;font-size:18px;">Khách hàng</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>


	</footer><!--/Footer-->
{% endblock %}
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/ajax.js' %}"></script>
    <script>
    function addCart(id){
            num = $("#number").val();
            if(!num){
                num = 1;
            }
            $.post('/addcart',{'id': id,'num': num, 'csrfmiddlewaretoken' :'{{csrf_token}}'}, function(data)
            {
                alert("Your cart had product!");
            });
    }
    function confirmCart() {
                var address = $("textarea[name='address']").text();
                var phone = $("input[name='phone']").text();
                var note = $("textarea[name='note']").text();
                $.post('/confirmCart', { 'address': address, 'phone': phone, 'note': note, 'csrfmiddlewaretoken': '{{csrf_token}}' }, function (data) {
                    alert(data);
                });
            }

    </script>
</body>
</html>

home/templates/cart.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
{% load mathfilters %}
<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>

            <div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Ảnh sản phẩm</td>
							<td class="description">Tên sản phẩm</td>
							<td class="price">Đơn giá</td>
							<td class="quantity">Số lượng</td>
							<td class="total">Thành tiền</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						{% for key,value in request.session.cart.items %}

						<tr>
							<td class="cart_product">
								<a href=""><img src="{{value.image}}" alt="" style="height:60px;width:60px"></a>
							</td>
							<td class="cart_title">
								<h4><a href="">{{value.name}}</a></h4>
							</td>
							<td class="cart_price">
								<p>{{value.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="{{value.num}}" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">{{value.price|mul:value.num}}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
						{% endfor %}
						<tr class="end">
							<td colspan="4">
								<a class="btn btn-default update" href="{% url 'home:product' %}" style="font-size: 20px">Cập nhật </a>
								<a class="btn btn-default check_out" href="{% url 'home:checkout' %}" style="font-size: 20px">Thanh toán </a>
							</td>
							<td colspan="2" class="text-danger text-left" >
								<strong style="font-size: 24px">{{total}}</strong>
							</td>
						</tr>
					</tbody>
				</table>
			</div>

		</div>
	</section> <!--/#cart_items-->
{% endblock content %}

home/templates/checkout.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
{% load mathfilters %}
<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Check out</li>
				</ol>
			</div><!--/breadcrums-->
			<form method="post" action="{% url 'home:confirmCart' %}">
				{% csrf_token %}
				<div class="form-group">
					<p>Thông tin khách hàng</p>
					<p>Khach hang :</p><input type="text" name="custom" value={{user.username}}  class="form-control">
					<p>Email :</p><input type="text" name="custom" value={{user.email}} class="form-control">
					<p>Dia chi :</p><input type="text" name="address" class="form-control">
					<p>SDT :</p><input type="text" name="phone" class="form-control">
					<p>Note :</p><input type="text" name="note" class="form-control">
					<br>
					<div class="table-responsive cart_info">
						<table class="table table-condensed">
										<thead>
											<tr class="cart_menu">
												<td class="image">Ảnh sản phẩm</td>
												<td class="description">Tên sản phẩm</td>
												<td class="price">Đơn giá</td>
												<td class="quantity">Số lượng</td>
												<td class="total">Thành tiền</td>
												<td></td>
											</tr>
										</thead>
										<tbody>
											{% for key,value in request.session.cart.items %}

											<tr>
												<td class="cart_product">
													<a href=""><img src="{{value.image}}" alt="" style="height:60px;width:60px"></a>
												</td>
												<td class="cart_title">
													<h4><a href="">{{value.name}}</a></h4>
												</td>
												<td class="cart_price">
													<p>{{value.price}}</p>
												</td>
												<td class="cart_quantity">
													<div class="cart_quantity_button">
														<a class="cart_quantity_up" href=""> + </a>
														<input class="cart_quantity_input" type="text" name="quantity" value="{{value.num}}" autocomplete="off" size="2">
														<a class="cart_quantity_down" href=""> - </a>
													</div>
												</td>
												<td class="cart_total">
													<p class="cart_total_price">{{value.price|mul:value.num}}</p>
												</td>
												<td class="cart_delete">
													<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
												</td>
											</tr>
											{% endfor %}
											<tr class="end">
												<td colspan="4">

													<h2 style="padding-left: 50px">Tổng tiền</h2>
												</td>
												<td colspan="2" class="text-danger text-left" >
													<strong style="font-size: 24px">{{total}}</strong>
												</td>
											</tr>
										</tbody>
									</table>
					</div>
				</div>
				<center><button type="submit" class="btn btn-primary">Gửi bình luận</button></center><br>
			</form>
			{% if  new_order %}
			<div class="alert alert-primary">
        		<div class="media-body">
				<h5 class="mt-0">Chào người dùng <a href="#">{{ custom }}</a> ! </h5>
				<p>don hang của bạn đã được gửi đi!
					Đợi quản trị viên xét duyệt nhe</p>
				</div>
			</div>
			{% endif %}

		</div>

	</section> <!--/#cart_items-->
{% endblock content %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% if user.is_authenticated %}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
				<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-12">
									<img src="{% static 'images/home/cafe1.jpg' %}" class="girl img-responsive" alt="" style="height:400px;width:1000px" />

								</div>
							</div>
							<div class="item">
								<div class="col-sm-12">
									<img src="{% static 'images/home/cafe6.jpg' %}" class="girl img-responsive" alt="" style="height:400px;width:1000px" />

								</div>
							</div>

							<div class="item">
								<div class="col-sm-12">
									<img src="{% static 'images/home/cafe7.jpg' %}" class="girl img-responsive" alt="" style="height:400px;width:1000px" />

								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Danh mục</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for item in categorys %}
                            <div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="{{ item.id }}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{ item.title }}
										</a>
									</h4>
								</div>

							</div>
                            {% endfor %}
						</div><!--/category-products-->
					

					
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Một số đồ uống</h2>
                        {% for item in products %}
                            <div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
                                            <a href="{% url 'home:detail' item.pk %}">
                                              <img src="{{ item.product_img }}" alt="" />
                                            </a>
											<h2>{{ item.price }}</h2>
											<a href="{% url 'home:detail' item.pk %}">
                                                <p>{{ item.title }}</p>
                                            </a>
											<a class="btn btn-default add-to-cart"  onclick="addCart({{detail.id}})"><i class="fa fa-shopping-cart" ></i>Thêm giỏ hàng</a>
										</div>

								</div>

							</div>
						</div>
                        {% endfor %}

					</div><!--features_items-->
					

					
				</div>
			</div>
		</div>
	</section>
{% else %}
    <center style="font-size: 20px"><div class="card my-4">
        <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary">Xin chào!</strong>
            <h3 class="mb-0">Chào mừng đến với CoffeeHouse !</h3>
            <p>Bạn cần có tài khoản để đăng nhập vào trang này</p>
            <p>Chưa có tài khoản?</p>
            <a href="{% url 'home:signup' %}" class="stretched-link">Đăng ký tài khoản</a>
        </div>
    </div>
		</center>
<br>
{% endif %}
{% endblock %}
	

	

  

home/templates/post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
<img class="img-fluid rounded" src="{{baiviet.anhbia}}" alt="" style="height: 700px;width: 1140px">

    <hr>

    <!-- Post Content -->
    <p class="lead" style="font-color:black">{{baiviet.noidung}}</p>
    <hr>
</div>
{% endblock %}

home/templates/shop.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Danh mục</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for item in categorys1 %}
                            <div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{ item.id }}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{ item.title }}
										</a>
									</h4>
								</div>

							</div>
                            {% endfor %}
						</div><!--/category-products-->



					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Một số đồ uống</h2>
                        {% for item in products1 %}
                            <div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
                                            <a href="{% url 'home:detail' item.pk %}">
                                              <img src="{{ item.product_img }}" alt="" />
                                            </a>
											<h2>{{ item.price }}</h2>
											<a href="{% url 'home:detail' item.pk %}">
                                                <p>{{ item.title }}</p>
                                            </a>
											<a class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Thêm giỏ hàng</a>
										</div>

								</div>

							</div>
						</div>
                        {% endfor %}

					</div><!--features_items-->



				</div>
			</div>
		</div>
	</section>
{% endblock %}